CREATE TABLE Migrations
(
    ID INTEGER PRIMARY KEY ASC AUTOINCREMENT NOT NULL,
    AppliedDate TEXT DEFAULT CURRENT_TIMESTAMP NOT NULL,
    Name TEXT NOT NULL
);

CREATE TABLE Recipes
(
    ID INTEGER PRIMARY KEY ASC AUTOINCREMENT NOT NULL,
    Name TEXT NOT NULL,
    CookTime INTEGER,
    Price INTEGER,
    ServingQuantity INTEGER,
    Instructions TEXT NOT NULL,
    CreationDate TEXT DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UpdatedDate TEXT DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE Ingredients
(
    ID INTEGER PRIMARY KEY ASC AUTOINCREMENT NOT NULL,
    Name TEXT NOT NULL
);

CREATE TABLE Tags
(
    ID INTEGER PRIMARY KEY ASC AUTOINCREMENT NOT NULL,
    Name TEXT NOT NULL
);

CREATE TABLE RecipeIngredient
(
    RecipeID INTEGER NOT NULL,
    IngredientID INTEGER NOT NULL,
    Measurement INTEGER,
    Quantity FLOAT,
    FOREIGN KEY(RecipeID) REFERENCES Recipes(ID),
    FOREIGN KEY(IngredientID) REFERENCES Ingredients(ID)
);

CREATE TABLE RecipeTag
(
    RecipeID INTEGER NOT NULL,
    TagID INTEGER NOT NULL,
    FOREIGN KEY(RecipeID) REFERENCES Recipes(ID),
    FOREIGN KEY(TagID) REFERENCES Tags(ID)
);
