CREATE TABLE Migrations
(
    Id INTEGER PRIMARY KEY ASC AUTOINCREMENT NOT NULL,
    Name TEXT NOT NULL,
    AppliedDate TEXT DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE Recipes
(
    Id INTEGER PRIMARY KEY ASC AUTOINCREMENT NOT NULL,
    Name TEXT NOT NULL,
    CookTime INTEGER,
    Price INTEGER,
    ServingQuantity INTEGER,
    Instructions TEXT NOT NULL,
    CreationDate TEXT DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UpdatedDate TEXT DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE Ingredients
(
    Id INTEGER PRIMARY KEY ASC AUTOINCREMENT NOT NULL,
    Name TEXT UNIQUE NOT NULL,
    PluralName TEXT UNIQUE
);

CREATE TABLE Tags
(
    Id INTEGER PRIMARY KEY ASC AUTOINCREMENT NOT NULL,
    Name TEXT NOT NULL,
    Description TEXT
);

CREATE TABLE RecipeIngredient
(
    RecipeId INTEGER NOT NULL,
    IngredientId INTEGER NOT NULL,
    Mass INTEGER,
    Volume INTEGER,
    Quantity FLOAT,
    PRIMARY KEY(RecipeId, IngredientId),
    FOREIGN KEY(RecipeId) REFERENCES Recipes(Id),
    FOREIGN KEY(IngredientId) REFERENCES Ingredients(Id)
);

CREATE TABLE RecipeTag
(
    RecipeId INTEGER NOT NULL,
    TagId INTEGER NOT NULL,
    PRIMARY KEY(RecipeId, TagId),
    FOREIGN KEY(RecipeId) REFERENCES Recipes(Id),
    FOREIGN KEY(TagId) REFERENCES Tags(Id)
);
